#!/bin/bash

set -e

echo
echo "=== DEPLOYING TO STAGING ==="
./deploy_tools/deploy_staging "$1"
sleep 0.5

echo
echo "=== RUNNING TEST SUITE AGAINST STAGING ==="
./test_staging

echo
echo "=== DEPLOYING TO PRODUCTION ==="
./deploy_tools/deploy_prod "$1"
