#!/bin/bash
# Run the functional test suite against the staging server.

if [[ $# -eq 0 ]]; then
  ARGS=test
else
  ARGS=$@
fi

# If you change anything, make sure that the script still returns the same exit code as
# this command.
TEST_URL=http://dev.django-showcase.haverford.edu pytest $ARGS
