#!/bin/bash
# Run the functional test suite against the staging server.
#
# IMPORTANT: Make sure this script always returns a non-zero exit code when the test suite
# fails.


if [[ $# -eq 0 ]]; then
  ARGS=test
else
  ARGS=$@
fi

TEST_URL=http://dev.django-showcase.haverford.edu pytest $ARGS
