#!/bin/bash
# Run the functional test suite against the staging server.
#
# If you change this file, make sure to change ./test_local as well!

if [[ $# -eq 0 ]]; then
  ARGS=test
else
  ARGS=$@
fi

TEST_URL=http://dev.django-showcase.haverford.edu pytest $ARGS
