#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.


# Make sure to update this variable as new packages are added.
PACKAGES="interns justhtml showcase_site tablebuilder test textviewer"
black --check $PACKAGES && flake8 $PACKAGES
