#!/bin/bash
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.


set -e

# Find all Python files, ignoring the virtual environment.
PY=$(find . -path ./.venv -prune -o -name "*.py" -print)

black --check $PY
flake8 $PY
