#!/bin/bash
#
# Run linters on all Python and JavaScript code.
#
# Whenever you do "git commit" this script is called, and if it exists with a non-zero status,
# the commit doesn't go through.
#
# See https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks for details.


# This line ensures that whenever one of the commands in this file exits with an error, the
# script as a whole does too.
set -e

# Find all Python files, ignoring the virtual environment.
PY=$(find . -path ./.venv -prune -o -name "*.py" -print)
black --check $PY
flake8 $PY

# If JSHint is installed, find all JavaScript files, ignoring the virtual environment
# (just in case).
if which jshint; then
  JS=$(find . -path ./.venv -prune -o -name "*.js" -print)
  jshint $JS
fi
