#!/bin/bash

set -e

if [[ $# -ne 0 ]]; then
  fab -f deploy_tools/fabfile.py "deploy:host=$1@dev.django-showcase.haverford.edu"
else
  fab -f deploy_tools/fabfile.py deploy:host=dev.django-showcase.haverford.edu
fi

if git tag | grep STAGING; then
  git tag -d STAGING
fi
git tag STAGING
