#!/bin/bash

set -e

deploy_live() {
  if [[ $# -ne 0 ]]; then
    fab -f deploy_tools/fabfile.py "deploy:host=$1@django-showcase.haverford.edu"
  else
    fab -f deploy_tools/fabfile.py deploy:host=django-showcase.haverford.edu
  fi

  git tag -d LIVE
  git tag LIVE
}

# Make sure we are on the master branch.
if ! (git branch | grep "* master") &> /dev/null; then
  echo "Error: not on master branch."
  exit
fi

# Make sure the STAGING tag points to HEAD, meaning that we have already deployed the
# latest changes to the staging server.
if ! diff -s .git/refs/heads/master .git/refs/tags/STAGING &>/dev/null; then
  echo "Error: have not deployed to staging server first."
  exit
fi

read -p "Have you run the staging tests? " yn
case $yn in
  [Yy]* ) deploy_live "$1";;
  [Nn]* ) ./test_staging && deploy_live "$1";;
  *     ) exit;;
esac
