#!/bin/bash

set -e

deploy_live() {
  fab -f deploy_tools/fabfile.py deploy:host=django-showcase.haverford.edu
  git tag -d LIVE
  git tag LIVE
}

read -p "Are you sure you want to deploy to the live server? " yn
case $yn in
  [Yy]* ) deploy_live;;
  *     ) exit;;
esac
